### PR TITLE
Megamorphic benchmark changes

### PR DESCRIPTION
**Pull request by shipilev**
Should be self-explanatory?

### CODE REVIEW

**Comment by shipilev** [comment]
Example output:
```
Benchmark               Mode  Cnt   Score   Error  Units
_000_DirectAccess       avgt   20   5.980 ± 0.006  ns/op
_100_Reflection         avgt   20  20.318 ± 0.912  ns/op
_200_MethodHandle       avgt   20  16.219 ± 0.295  ns/op
_300_JavaCompiler       avgt   20  12.319 ± 0.003  ns/op
_400_LamdbaMetafactory  avgt   20  13.182 ± 0.004  ns/op

```

**Comment by ge0ffrey** [comment]
thank you
So my original MegamorphicFasterReflectionClientBenchmark wasn't megamorphic for the BPR? Might it be be megamorphic for the Function (= old GetterFunction) used in the LambdaBRP?

I'll merge your code (today or tomorrow morning) but first take a copy of my orginal test - I don't care about this megamorphic use case much personally: in reality, if an optaplanner users lambda BRP's for 1 getter, he'll use a lambda BRP for every getter, mixing is very rare. But of course, there are many different getters, so there will be many different Function implementations. So metaspace, boostrap impact etc matters.

**Comment by shipilev** [comment]
Your original benchmark was megamorphic somehwere inside *BPR themselves. The code like in the benchmark protects from accidental class specialization (e.g. if you accidentally call different BPR classes). This, I think, reflects the real case more accurately.

**Comment by ge0ffrey** [comment]
Merged, thanks Shipilev. I first copied mine in MultiGetterFasterReflectionClientBenchmark

**Pull request merged**
